import { app, BrowserWindow, ipcMain, session } from "electron";
import serve from "electron-serve";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  downloadYoutubeVideo,
  hasSavedCookies,
  saveCookiesFile,
  clearCookiesFile,
} from "./youtube-downloader.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const appServe = serve({ directory: path.join(__dirname, "out") });

let mainWindow = null;

const createWindow = () => {
  const win = new BrowserWindow({
    width: 1200,
    height: 800,
    webPreferences: {
      preload: path.join(__dirname, "preload.js"),
      nodeIntegration: false,
      contextIsolation: true,
    },
  });

  mainWindow = win;

  appServe(win)
    .then(() => {
      win.loadURL("app://-");
      if (!app.isPackaged) {
        win.webContents.openDevTools();
      }
    })
    .catch((err) => {
      console.error("Failed to serve app:", err);
    });
};

function setupIpcHandlers() {
  ipcMain.handle("youtube:check-cookies", () => {
    return { hasCookies: hasSavedCookies() };
  });

  ipcMain.handle("youtube:save-cookies", (_event, cookiesText) => {
    saveCookiesFile(cookiesText);
    return { success: true };
  });

  ipcMain.handle("youtube:clear-cookies", () => {
    clearCookiesFile();
    return { success: true };
  });

  ipcMain.handle("youtube:download", async (_event, url) => {
    try {
      const result = await downloadYoutubeVideo(url, (progress) => {
        if (mainWindow && !mainWindow.isDestroyed()) {
          mainWindow.webContents.send("youtube:progress", progress);
        }
      });
      return { success: true, data: result };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return { success: false, error: msg };
    }
  });

  ipcMain.handle("youtube:google-login", async () => {
    return new Promise((resolve) => {
      const authWindow = new BrowserWindow({
        width: 650,
        height: 750,
        parent: mainWindow || undefined,
        modal: true,
        autoHideMenuBar: true,
        title: "Sign in with Google",
        webPreferences: {
          nodeIntegration: false,
          contextIsolation: true,
          partition: "persist:youtube_auth",
        },
      });

      authWindow.loadURL(
        "https://accounts.google.com/AccountChooser?service=youtube&continue=https%3A%2F%2Fwww.youtube.com%2Fsignin%3Faction_handle_signin%3Dtrue",
        {
          userAgent:
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36",
        },
      );

      let resolved = false;

      const finishWithCookies = async (windowAlreadyClosed = false) => {
        if (resolved) return;
        resolved = true;
        try {
          const authSession = session.fromPartition("persist:youtube_auth");
          await authSession.cookies.flushStore();

          const allCookies = await authSession.cookies.get({});
          const ytCookies = allCookies.filter(
            (c) =>
              c.domain.includes("youtube.com") ||
              c.domain.includes("google.com"),
          );

          if (ytCookies.length > 0) {
            let netscape =
              "# Netscape HTTP Cookie File\n# http://curl.haxx.se/rfc/cookie_spec.html\n# This file was generated by VidToPDF\n";
            for (const c of ytCookies) {
              const domain = c.domain.startsWith(".")
                ? c.domain
                : `.${c.domain}`;
              const includeSubdomains = "TRUE";
              const path = c.path || "/";
              const secure = c.secure ? "TRUE" : "FALSE";
              const expiry = Math.floor(
                c.expirationDate || Date.now() / 1000 + 86400 * 30,
              );
              netscape += `${domain}\t${includeSubdomains}\t${path}\t${secure}\t${expiry}\t${c.name}\t${c.value}\n`;
            }

            saveCookiesFile(netscape);
          }

          if (!windowAlreadyClosed && !authWindow.isDestroyed()) {
            authWindow.close();
          }
          resolve({ success: ytCookies.length > 0, count: ytCookies.length });
        } catch (e) {
          resolve({ success: false, error: e?.message || String(e) });
        }
      };

      authWindow.webContents.on("did-navigate", (_event, navUrl) => {
        if (
          navUrl.includes("youtube.com") &&
          !navUrl.includes("accounts.google.com")
        ) {
          setTimeout(() => finishWithCookies(false), 1500);
        }
      });

      authWindow.on("closed", () => {
        finishWithCookies(true);
      });
    });
  });
}

app.whenReady().then(() => {
  setupIpcHandlers();
  createWindow();

  app.on("activate", () => {
    if (BrowserWindow.getAllWindows().length === 0) {
      createWindow();
    }
  });
});

app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});
