import { app, BrowserWindow, ipcMain, session } from "electron";
import serve from "electron-serve";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  downloadYoutubeVideo,
  hasSavedCookies,
  saveCookiesFile,
  clearCookiesFile,
} from "./youtube-downloader.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const appServe = serve({ directory: path.join(__dirname, "out") });

let mainWindow = null;

const createWindow = () => {
  const win = new BrowserWindow({
    width: 1200,
    height: 800,
    webPreferences: {
      preload: path.join(__dirname, "preload.js"),
      nodeIntegration: false,
      contextIsolation: true,
    },
  });

  mainWindow = win;

  appServe(win)
    .then(() => {
      win.loadURL("app://-");
      if (!app.isPackaged) {
        win.webContents.openDevTools();
      }
    })
    .catch((err) => {
      console.error("Failed to serve app:", err);
    });
};

function setupIpcHandlers() {
  ipcMain.handle("youtube:check-cookies", () => {
    return { hasCookies: hasSavedCookies() };
  });

  ipcMain.handle("youtube:save-cookies", (_event, cookiesText) => {
    saveCookiesFile(cookiesText);
    return { success: true };
  });

  ipcMain.handle("youtube:clear-cookies", () => {
    clearCookiesFile();
    return { success: true };
  });

  ipcMain.handle("youtube:download", async (_event, url) => {
    try {
      const result = await downloadYoutubeVideo(url, (progress) => {
        if (mainWindow && !mainWindow.isDestroyed()) {
          mainWindow.webContents.send("youtube:progress", progress);
        }
      });
      return { success: true, data: result };
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      return { success: false, error: msg };
    }
  });

  ipcMain.handle("youtube:google-login", async () => {
    return new Promise((resolve) => {
      const authWindow = new BrowserWindow({
        width: 600,
        height: 700,
        parent: mainWindow || undefined,
        modal: true,
        webPreferences: {
          nodeIntegration: false,
          contextIsolation: true,
        },
      });

      authWindow.loadURL(
        "https://accounts.google.com/ServiceLogin?service=youtube",
      );

      let resolved = false;

      const finishWithCookies = async () => {
        if (resolved) return;
        resolved = true;
        try {
          const cookies = await session.defaultSession.cookies.get({
            domain: ".youtube.com",
          });
          const googleCookies = await session.defaultSession.cookies.get({
            domain: ".google.com",
          });
          const allCookies = [...cookies, ...googleCookies];

          let netscape =
            "# Netscape HTTP Cookie File\n# http://curl.haxx.se/rfc/cookie_spec.html\n# This file was generated by VidToPDF\n";
          for (const c of allCookies) {
            const domain = c.domain.startsWith(".") ? c.domain : `.${c.domain}`;
            const includeSubdomains = "TRUE";
            const path = c.path || "/";
            const secure = c.secure ? "TRUE" : "FALSE";
            const expiry = Math.floor(
              c.expirationDate || Date.now() / 1000 + 86400 * 30,
            );
            netscape += `${domain}\t${includeSubdomains}\t${path}\t${secure}\t${expiry}\t${c.name}\t${c.value}\n`;
          }

          saveCookiesFile(netscape);
          authWindow.close();
          resolve({ success: true, count: allCookies.length });
        } catch (e) {
          resolve({ success: false, error: e?.message || String(e) });
        }
      };

      authWindow.webContents.on("did-navigate", (_event, navUrl) => {
        if (
          navUrl.includes("youtube.com") &&
          !navUrl.includes("accounts.google.com")
        ) {
          setTimeout(finishWithCookies, 1500);
        }
      });

      authWindow.on("closed", () => {
        if (!resolved) {
          resolved = true;
          resolve({ success: hasSavedCookies() });
        }
      });
    });
  });
}

app.whenReady().then(() => {
  setupIpcHandlers();
  createWindow();

  app.on("activate", () => {
    if (BrowserWindow.getAllWindows().length === 0) {
      createWindow();
    }
  });
});

app.on("window-all-closed", () => {
  if (process.platform !== "darwin") {
    app.quit();
  }
});
